/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SushiIndexRouteImport } from './routes/sushi/index'
import { Route as SouseIndexRouteImport } from './routes/souse/index'
import { Route as SneaksIndexRouteImport } from './routes/sneaks/index'
import { Route as PitsaIndexRouteImport } from './routes/pitsa/index'
import { Route as JusiecIndexRouteImport } from './routes/jusiec/index'
import { Route as DesertIndexRouteImport } from './routes/desert/index'
import { Route as ComboIndexRouteImport } from './routes/combo/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SushiIndexRoute = SushiIndexRouteImport.update({
  id: '/sushi/',
  path: '/sushi/',
  getParentRoute: () => rootRouteImport,
} as any)
const SouseIndexRoute = SouseIndexRouteImport.update({
  id: '/souse/',
  path: '/souse/',
  getParentRoute: () => rootRouteImport,
} as any)
const SneaksIndexRoute = SneaksIndexRouteImport.update({
  id: '/sneaks/',
  path: '/sneaks/',
  getParentRoute: () => rootRouteImport,
} as any)
const PitsaIndexRoute = PitsaIndexRouteImport.update({
  id: '/pitsa/',
  path: '/pitsa/',
  getParentRoute: () => rootRouteImport,
} as any)
const JusiecIndexRoute = JusiecIndexRouteImport.update({
  id: '/jusiec/',
  path: '/jusiec/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesertIndexRoute = DesertIndexRouteImport.update({
  id: '/desert/',
  path: '/desert/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComboIndexRoute = ComboIndexRouteImport.update({
  id: '/combo/',
  path: '/combo/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/combo/': typeof ComboIndexRoute
  '/desert/': typeof DesertIndexRoute
  '/jusiec/': typeof JusiecIndexRoute
  '/pitsa/': typeof PitsaIndexRoute
  '/sneaks/': typeof SneaksIndexRoute
  '/souse/': typeof SouseIndexRoute
  '/sushi/': typeof SushiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/combo': typeof ComboIndexRoute
  '/desert': typeof DesertIndexRoute
  '/jusiec': typeof JusiecIndexRoute
  '/pitsa': typeof PitsaIndexRoute
  '/sneaks': typeof SneaksIndexRoute
  '/souse': typeof SouseIndexRoute
  '/sushi': typeof SushiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/combo/': typeof ComboIndexRoute
  '/desert/': typeof DesertIndexRoute
  '/jusiec/': typeof JusiecIndexRoute
  '/pitsa/': typeof PitsaIndexRoute
  '/sneaks/': typeof SneaksIndexRoute
  '/souse/': typeof SouseIndexRoute
  '/sushi/': typeof SushiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/combo/'
    | '/desert/'
    | '/jusiec/'
    | '/pitsa/'
    | '/sneaks/'
    | '/souse/'
    | '/sushi/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/combo'
    | '/desert'
    | '/jusiec'
    | '/pitsa'
    | '/sneaks'
    | '/souse'
    | '/sushi'
  id:
    | '__root__'
    | '/'
    | '/combo/'
    | '/desert/'
    | '/jusiec/'
    | '/pitsa/'
    | '/sneaks/'
    | '/souse/'
    | '/sushi/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComboIndexRoute: typeof ComboIndexRoute
  DesertIndexRoute: typeof DesertIndexRoute
  JusiecIndexRoute: typeof JusiecIndexRoute
  PitsaIndexRoute: typeof PitsaIndexRoute
  SneaksIndexRoute: typeof SneaksIndexRoute
  SouseIndexRoute: typeof SouseIndexRoute
  SushiIndexRoute: typeof SushiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sushi/': {
      id: '/sushi/'
      path: '/sushi'
      fullPath: '/sushi/'
      preLoaderRoute: typeof SushiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/souse/': {
      id: '/souse/'
      path: '/souse'
      fullPath: '/souse/'
      preLoaderRoute: typeof SouseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sneaks/': {
      id: '/sneaks/'
      path: '/sneaks'
      fullPath: '/sneaks/'
      preLoaderRoute: typeof SneaksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pitsa/': {
      id: '/pitsa/'
      path: '/pitsa'
      fullPath: '/pitsa/'
      preLoaderRoute: typeof PitsaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jusiec/': {
      id: '/jusiec/'
      path: '/jusiec'
      fullPath: '/jusiec/'
      preLoaderRoute: typeof JusiecIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desert/': {
      id: '/desert/'
      path: '/desert'
      fullPath: '/desert/'
      preLoaderRoute: typeof DesertIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combo/': {
      id: '/combo/'
      path: '/combo'
      fullPath: '/combo/'
      preLoaderRoute: typeof ComboIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComboIndexRoute: ComboIndexRoute,
  DesertIndexRoute: DesertIndexRoute,
  JusiecIndexRoute: JusiecIndexRoute,
  PitsaIndexRoute: PitsaIndexRoute,
  SneaksIndexRoute: SneaksIndexRoute,
  SouseIndexRoute: SouseIndexRoute,
  SushiIndexRoute: SushiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
